// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.gvsig.framework.web.ogc;

import java.io.Serializable;

privileged aspect ContactAddressMetadata_Roo_Serializable {

    declare parents: ContactAddressMetadata implements Serializable;

    private static final long ContactAddressMetadata.serialVersionUID = 1L;

}
