// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.gvsig.framework.web.ogc;

import org.gvsig.framework.web.ogc.WMTSInfo;
import java.io.Serializable;

privileged aspect WMTSInfo_Roo_Serializable {
    
    declare parents: WMTSInfo implements Serializable;
    
    private static final long WMTSInfo.serialVersionUID = 1L;
    
}
